In [4]:
import pandas as pd
df = pd.read_csv("Resources/Week3-Day2-Activity6-people.csv")

In [9]:
df.shape
df.head()

,first_name,last_name,gender,age,company_name,address,city,county,postal,phone1,phone2,email,web
0,Aleshia,Tomkiewicz,F,54,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk
1,Evan,Zigomalas,M,47,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk
2,France,Andrade,M,42,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk
3,Ulysses,Mcwalters,M,45,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk
4,Tyisha,Veness,F,37,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk

In [10]:
# iloc is index location
# loc is location if index is not a numner
df.iloc[0]

first_name                                   Aleshia
last_name                                 Tomkiewicz
gender                                             F
age                                               54
company_name                 Alan D Rosenburg Cpa Pc
address                                 14 Taylor St
city                               St. Stephens Ward
county                                          Kent
postal                                       CT2 7PP
phone1                                  01835-703597
phone2                                  01944-369967
email                        atomkiewicz@hotmail.com
web             http://www.alandrosenburgcpapc.co.uk
Name: 0, dtype: object

In [11]:
df.iloc[1]

first_name                                   Evan
last_name                               Zigomalas
gender                                          M
age                                            47
company_name                   Cap Gemini America
address                               5 Binney St
city                                   Abbey Ward
county                            Buckinghamshire
postal                                   HP11 2AX
phone1                               01937-864715
phone2                               01714-737668
email                    evan.zigomalas@gmail.com
web             http://www.capgeminiamerica.co.uk
Name: 1, dtype: object

In [12]:
#this will get you the first 10 elements
df.iloc[0:10]

,first_name,last_name,gender,age,company_name,address,city,county,postal,phone1,phone2,email,web
0,Aleshia,Tomkiewicz,F,54,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk
1,Evan,Zigomalas,M,47,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk
2,France,Andrade,M,42,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk
3,Ulysses,Mcwalters,M,45,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk
4,Tyisha,Veness,F,37,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk
5,Eric,Rampy,M,28,"Thompson, Michael C Esq",9472 Lind St,Desborough,Northamptonshire,NN14 2GH,01969-886290,01545-817375,erampy@rampy.co.uk,http://www.thompsonmichaelcesq.co.uk
6,Marg,Grasmick,F,44,Wrangle Hill Auto Auct & Slvg,7457 Cowl St #70,Bargate Ward,Southampton,SO14 3TY,01865-582516,01362-620532,marg@hotmail.com,http://www.wranglehillautoauctslvg.co.uk
7,Laquita,Hisaw,F,40,In Communications Inc,20 Gloucester Pl #96,Chirton Ward,Tyne & Wear,NE29 7AD,01746-394243,01590-982428,laquita@yahoo.com,http://www.incommunicationsinc.co.uk
8,Lura,Manzella,F,53,Bizerba Usa Inc,929 Augustine St,Staple Hill Ward,South Gloucestershire,BS16 4LL,01907-538509,01340-713951,lura@hotmail.com,http://www.bizerbausainc.co.uk
9,Yuette,Klapec,F,55,Max Video,45 Bradfield St #166,Parwich,Derbyshire,DE6 1QN,01903-649460,01933-512513,yuette.klapec@klapec.co.uk,http://www.maxvideo.co.uk

In [37]:
df.iloc[len(df)-1] # is the same as df.iloc[-1]

first_name                                               Mi
last_name                                            Richan
gender                                                    M
age                                                      27
company_name                 Nelson Wright Haworth Golf Crs
address                                     6 Norwood Grove
city                                      Tanworth-in-Arden
county                                         Warwickshire
postal                                              B94 5RZ
phone1                                         01451-785624
phone2                                         01202-738406
email                                        mi@hotmail.com
web             http://www.nelsonwrighthaworthgolfcrs.co.uk
Name: 499, dtype: object

In [38]:
df.iloc[-1]

first_name                                               Mi
last_name                                            Richan
gender                                                    M
age                                                      27
company_name                 Nelson Wright Haworth Golf Crs
address                                     6 Norwood Grove
city                                      Tanworth-in-Arden
county                                         Warwickshire
postal                                              B94 5RZ
phone1                                         01451-785624
phone2                                         01202-738406
email                                        mi@hotmail.com
web             http://www.nelsonwrighthaworthgolfcrs.co.uk
Name: 499, dtype: object

In [39]:
print(df.iloc[-1] )

first_name                                               Mi
last_name                                            Richan
gender                                                    M
age                                                      27
company_name                 Nelson Wright Haworth Golf Crs
address                                     6 Norwood Grove
city                                      Tanworth-in-Arden
county                                         Warwickshire
postal                                              B94 5RZ
phone1                                         01451-785624
phone2                                         01202-738406
email                                        mi@hotmail.com
web             http://www.nelsonwrighthaworthgolfcrs.co.uk
Name: 499, dtype: object

In [40]:
df.index

RangeIndex(start=0, stop=500, step=1)

In [41]:
# dictionary with list object in values
details = {
    'Name' : ['Ankit', 'Aishwarya', 'Shaurya', 'Shivangi'],
    'Age' : [23, 21, 22, 21],
    'University' : ['BHU', 'JNU', 'DU', 'BHU'],
}
  
# creating a Dataframe object 
df_example = pd.DataFrame(details)

In [42]:
df_example

        Name  Age University
0      Ankit   23        BHU
1  Aishwarya   21        JNU
2    Shaurya   22         DU
3   Shivangi   21        BHU

In [43]:
# here ,1 shows the column
df.iloc[:,1]

0      Tomkiewicz
1       Zigomalas
2         Andrade
3       Mcwalters
4          Veness
          ...
495          Veit
496       Euresti
497      Brenning
498         Keeny
499        Richan
Name: last_name, Length: 500, dtype: object

In [44]:
# here ,1 to 5shows the column
df.iloc[:,1:5]

      last_name gender  age                    company_name
0    Tomkiewicz      F   54         Alan D Rosenburg Cpa Pc
1     Zigomalas      M   47              Cap Gemini America
2       Andrade      M   42             Elliott, John W Esq
3     Mcwalters      M   45                  Mcmahan, Ben L
4        Veness      F   37                  Champagne Room
..          ...    ...  ...                             ...
495        Veit      M   38      Plaza Gourmet Delicatessen
496     Euresti      M   56            Fitzgerald, Edward J
497    Brenning      F   31              Furey & Associates
498       Keeny      F   41        Bfg Federal Credit Union
499      Richan      M   27  Nelson Wright Haworth Golf Crs

[500 rows x 4 columns]

In [45]:
#this will take roses 5 to 10 and columns 1 to 5
df.iloc[5:10,1:5]

  last_name gender  age                   company_name
5     Rampy      M   28        Thompson, Michael C Esq
6  Grasmick      F   44  Wrangle Hill Auto Auct & Slvg
7     Hisaw      F   40          In Communications Inc
8  Manzella      F   53                Bizerba Usa Inc
9    Klapec      F   55                      Max Video

In [47]:
df[df['age']>50]

,first_name,last_name,gender,age,company_name,address,city,county,postal,phone1,phone2,email,web
0,Aleshia,Tomkiewicz,F,54,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk
8,Lura,Manzella,F,53,Bizerba Usa Inc,929 Augustine St,Staple Hill Ward,South Gloucestershire,BS16 4LL,01907-538509,01340-713951,lura@hotmail.com,http://www.bizerbausainc.co.uk
9,Yuette,Klapec,F,55,Max Video,45 Bradfield St #166,Parwich,Derbyshire,DE6 1QN,01903-649460,01933-512513,yuette.klapec@klapec.co.uk,http://www.maxvideo.co.uk
15,Michell,Throssell,M,54,Weiss Spirt & Guyer,89 Noon St,Carbrooke,Norfolk,IP25 6JQ,01967-580851,01672-496478,mthrossell@throssell.co.uk,http://www.weissspirtguyer.co.uk
20,Peter,Gutierres,M,55,Niagara Custombuilt Mfg Co,4410 Tarlton St,Prestatyn Community,Denbighshire,LL19 9EG,01842-767201,01859-648598,peter_gutierres@yahoo.com,http://www.niagaracustombuiltmfgco.co.uk
...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,Isabelle,Kono,F,58,Rock Springs Petroleum Equip,4920 Fazakerley Rd,Plymstock Dunstone Ward,Devon,PL9 8RD,01552-682601,01953-816728,isabelle.kono@yahoo.com,http://www.rockspringspetroleumequip.co.uk
488,Ronnie,Brigman,M,57,Howard Johnson,6 Morley St,Batchwood Ward,Hertfordshire,AL3 5JN,01943-754681,01972-686199,ronnie@brigman.co.uk,http://www.howardjohnson.co.uk
492,Elbert,Fiorino,M,53,"Donald, G Nelson Esq",726 Westmoreland Place,Ballochmyle Ward,East Ayrshire,KA5 6EL,01724-467889,01992-537553,elbert@hotmail.com,http://www.donaldgnelsonesq.co.uk
493,Pura,Manciel,F,54,Cia Inspection,7 Water St,Priory Heath Ward,Suffolk,IP3 9RB,01853-412588,01386-437186,pura.manciel@yahoo.com,http://www.ciainspection.co.uk
496,Reid,Euresti,M,56,"Fitzgerald, Edward J",70 Foster St,Inverness Ness-Side Ward,Highland,IV2 6WT,01916-963261,01370-319414,reuresti@euresti.co.uk,http://www.fitzgeraldedwardj.co.uk

In [48]:
df[(df['age']>50) & (df['first_name']=="Aleshia")]

,first_name,last_name,gender,age,company_name,address,city,county,postal,phone1,phone2,email,web
0,Aleshia,Tomkiewicz,F,54,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk

In [51]:
df['fullname'] = df['first_name'] + " " + df['last_name']

In [52]:
df

,first_name,last_name,gender,age,company_name,address,city,county,postal,phone1,phone2,email,web,fullname
0,Aleshia,Tomkiewicz,F,54,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk,Aleshia Tomkiewicz
1,Evan,Zigomalas,M,47,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk,Evan Zigomalas
2,France,Andrade,M,42,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk,France Andrade
3,Ulysses,Mcwalters,M,45,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk,Ulysses Mcwalters
4,Tyisha,Veness,F,37,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk,Tyisha Veness
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Avery,Veit,M,38,Plaza Gourmet Delicatessen,9166 Devon St #905,Knightsbridge and Belgravia Wa,Greater London,SW1W 8JY,01748-625058,01369-185737,avery@veit.co.uk,http://www.plazagourmetdelicatessen.co.uk,Avery Veit
496,Reid,Euresti,M,56,"Fitzgerald, Edward J",70 Foster St,Inverness Ness-Side Ward,Highland,IV2 6WT,01916-963261,01370-319414,reuresti@euresti.co.uk,http://www.fitzgeraldedwardj.co.uk,Reid Euresti
497,Charlette,Brenning,F,31,Furey & Associates,714 Fonthill Rd,Darton West Ward,South Yorkshire,S75 5EJ,01888-152110,01301-312487,cbrenning@brenning.co.uk,http://www.fureyassociates.co.uk,Charlette Brenning
498,Celestina,Keeny,F,41,Bfg Federal Credit Union,9 Milton St,Consett North ED,County Durham,DH8 5LP,01877-379681,01600-463475,celestina_keeny@gmail.com,http://www.bfgfederalcreditunion.co.uk,Celestina Keeny
499,Mi,Richan,M,27,Nelson Wright Haworth Golf Crs,6 Norwood Grove,Tanworth-in-Arden,Warwickshire,B94 5RZ,01451-785624,01202-738406,mi@hotmail.com,http://www.nelsonwrighthaworthgolfcrs.co.uk,Mi Richan

In [56]:
df.set_index('fullname',inplace=False)

,first_name,last_name,gender,age,company_name,address,city,county,postal,phone1,phone2,email,web
fullname,,,,,,,,,,,,,
Aleshia Tomkiewicz,Aleshia,Tomkiewicz,F,54,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk
Evan Zigomalas,Evan,Zigomalas,M,47,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk
France Andrade,France,Andrade,M,42,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk
Ulysses Mcwalters,Ulysses,Mcwalters,M,45,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk
Tyisha Veness,Tyisha,Veness,F,37,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Avery Veit,Avery,Veit,M,38,Plaza Gourmet Delicatessen,9166 Devon St #905,Knightsbridge and Belgravia Wa,Greater London,SW1W 8JY,01748-625058,01369-185737,avery@veit.co.uk,http://www.plazagourmetdelicatessen.co.uk
Reid Euresti,Reid,Euresti,M,56,"Fitzgerald, Edward J",70 Foster St,Inverness Ness-Side Ward,Highland,IV2 6WT,01916-963261,01370-319414,reuresti@euresti.co.uk,http://www.fitzgeraldedwardj.co.uk
Charlette Brenning,Charlette,Brenning,F,31,Furey & Associates,714 Fonthill Rd,Darton West Ward,South Yorkshire,S75 5EJ,01888-152110,01301-312487,cbrenning@brenning.co.uk,http://www.fureyassociates.co.uk
Celestina Keeny,Celestina,Keeny,F,41,Bfg Federal Credit Union,9 Milton St,Consett North ED,County Durham,DH8 5LP,01877-379681,01600-463475,celestina_keeny@gmail.com,http://www.bfgfederalcreditunion.co.uk
Mi Richan,Mi,Richan,M,27,Nelson Wright Haworth Golf Crs,6 Norwood Grove,Tanworth-in-Arden,Warwickshire,B94 5RZ,01451-785624,01202-738406,mi@hotmail.com,http://www.nelsonwrighthaworthgolfcrs.co.uk

In [57]:
df.index

RangeIndex(start=0, stop=500, step=1)

In [58]:
df.set_index('fullname',inplace=True)

In [59]:
df.index

Index(['Aleshia Tomkiewicz', 'Evan Zigomalas', 'France Andrade',
       'Ulysses Mcwalters', 'Tyisha Veness', 'Eric Rampy', 'Marg Grasmick',
       'Laquita Hisaw', 'Lura Manzella', 'Yuette Klapec',
       ...
       'Rosita Ausdemore', 'Huey Stancil', 'Elbert Fiorino', 'Pura Manciel',
       'Alesia Katie', 'Avery Veit', 'Reid Euresti', 'Charlette Brenning',
       'Celestina Keeny', 'Mi Richan'],
      dtype='object', name='fullname', length=500)

In [61]:
df = df.reset_index(level=0, drop=True).reset_index()

In [62]:
df.index

RangeIndex(start=0, stop=500, step=1)

In [63]:
df

,index,first_name,last_name,gender,age,company_name,address,city,county,postal,phone1,phone2,email,web
0,0,Aleshia,Tomkiewicz,F,54,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk
1,1,Evan,Zigomalas,M,47,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk
2,2,France,Andrade,M,42,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk
3,3,Ulysses,Mcwalters,M,45,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk
4,4,Tyisha,Veness,F,37,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,Avery,Veit,M,38,Plaza Gourmet Delicatessen,9166 Devon St #905,Knightsbridge and Belgravia Wa,Greater London,SW1W 8JY,01748-625058,01369-185737,avery@veit.co.uk,http://www.plazagourmetdelicatessen.co.uk
496,496,Reid,Euresti,M,56,"Fitzgerald, Edward J",70 Foster St,Inverness Ness-Side Ward,Highland,IV2 6WT,01916-963261,01370-319414,reuresti@euresti.co.uk,http://www.fitzgeraldedwardj.co.uk
497,497,Charlette,Brenning,F,31,Furey & Associates,714 Fonthill Rd,Darton West Ward,South Yorkshire,S75 5EJ,01888-152110,01301-312487,cbrenning@brenning.co.uk,http://www.fureyassociates.co.uk
498,498,Celestina,Keeny,F,41,Bfg Federal Credit Union,9 Milton St,Consett North ED,County Durham,DH8 5LP,01877-379681,01600-463475,celestina_keeny@gmail.com,http://www.bfgfederalcreditunion.co.uk
499,499,Mi,Richan,M,27,Nelson Wright Haworth Golf Crs,6 Norwood Grove,Tanworth-in-Arden,Warwickshire,B94 5RZ,01451-785624,01202-738406,mi@hotmail.com,http://www.nelsonwrighthaworthgolfcrs.co.uk

In [64]:
df.drop(columns='index', inplace=True)

In [65]:
df

,first_name,last_name,gender,age,company_name,address,city,county,postal,phone1,phone2,email,web
0,Aleshia,Tomkiewicz,F,54,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk
1,Evan,Zigomalas,M,47,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk
2,France,Andrade,M,42,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk
3,Ulysses,Mcwalters,M,45,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk
4,Tyisha,Veness,F,37,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Avery,Veit,M,38,Plaza Gourmet Delicatessen,9166 Devon St #905,Knightsbridge and Belgravia Wa,Greater London,SW1W 8JY,01748-625058,01369-185737,avery@veit.co.uk,http://www.plazagourmetdelicatessen.co.uk
496,Reid,Euresti,M,56,"Fitzgerald, Edward J",70 Foster St,Inverness Ness-Side Ward,Highland,IV2 6WT,01916-963261,01370-319414,reuresti@euresti.co.uk,http://www.fitzgeraldedwardj.co.uk
497,Charlette,Brenning,F,31,Furey & Associates,714 Fonthill Rd,Darton West Ward,South Yorkshire,S75 5EJ,01888-152110,01301-312487,cbrenning@brenning.co.uk,http://www.fureyassociates.co.uk
498,Celestina,Keeny,F,41,Bfg Federal Credit Union,9 Milton St,Consett North ED,County Durham,DH8 5LP,01877-379681,01600-463475,celestina_keeny@gmail.com,http://www.bfgfederalcreditunion.co.uk
499,Mi,Richan,M,27,Nelson Wright Haworth Golf Crs,6 Norwood Grove,Tanworth-in-Arden,Warwickshire,B94 5RZ,01451-785624,01202-738406,mi@hotmail.com,http://www.nelsonwrighthaworthgolfcrs.co.uk

In [66]:
df.set_index('first_name',inplace=True)
df

,last_name,gender,age,company_name,address,city,county,postal,phone1,phone2,email,web
first_name,,,,,,,,,,,,
Aleshia,Tomkiewicz,F,54,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk
Evan,Zigomalas,M,47,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk
France,Andrade,M,42,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk
Ulysses,Mcwalters,M,45,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk
Tyisha,Veness,F,37,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk
...,...,...,...,...,...,...,...,...,...,...,...,...
Avery,Veit,M,38,Plaza Gourmet Delicatessen,9166 Devon St #905,Knightsbridge and Belgravia Wa,Greater London,SW1W 8JY,01748-625058,01369-185737,avery@veit.co.uk,http://www.plazagourmetdelicatessen.co.uk
Reid,Euresti,M,56,"Fitzgerald, Edward J",70 Foster St,Inverness Ness-Side Ward,Highland,IV2 6WT,01916-963261,01370-319414,reuresti@euresti.co.uk,http://www.fitzgeraldedwardj.co.uk
Charlette,Brenning,F,31,Furey & Associates,714 Fonthill Rd,Darton West Ward,South Yorkshire,S75 5EJ,01888-152110,01301-312487,cbrenning@brenning.co.uk,http://www.fureyassociates.co.uk
Celestina,Keeny,F,41,Bfg Federal Credit Union,9 Milton St,Consett North ED,County Durham,DH8 5LP,01877-379681,01600-463475,celestina_keeny@gmail.com,http://www.bfgfederalcreditunion.co.uk
Mi,Richan,M,27,Nelson Wright Haworth Golf Crs,6 Norwood Grove,Tanworth-in-Arden,Warwickshire,B94 5RZ,01451-785624,01202-738406,mi@hotmail.com,http://www.nelsonwrighthaworthgolfcrs.co.uk

In [67]:
df.loc['Aleshia']

last_name                                 Tomkiewicz
gender                                             F
age                                               54
company_name                 Alan D Rosenburg Cpa Pc
address                                 14 Taylor St
city                               St. Stephens Ward
county                                          Kent
postal                                       CT2 7PP
phone1                                  01835-703597
phone2                                  01944-369967
email                        atomkiewicz@hotmail.com
web             http://www.alandrosenburgcpapc.co.uk
Name: Aleshia, dtype: object

In [68]:
#how to change the county for Aleshia
df.loc['Aleshia','county']

'Kent'

In [69]:
df.loc['Aleshia','county'] = "Toronto"
df.loc['Aleshia','county']

'Toronto'

In [70]:
df

,last_name,gender,age,company_name,address,city,county,postal,phone1,phone2,email,web
first_name,,,,,,,,,,,,
Aleshia,Tomkiewicz,F,54,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Toronto,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk
Evan,Zigomalas,M,47,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk
France,Andrade,M,42,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk
Ulysses,Mcwalters,M,45,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk
Tyisha,Veness,F,37,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk
...,...,...,...,...,...,...,...,...,...,...,...,...
Avery,Veit,M,38,Plaza Gourmet Delicatessen,9166 Devon St #905,Knightsbridge and Belgravia Wa,Greater London,SW1W 8JY,01748-625058,01369-185737,avery@veit.co.uk,http://www.plazagourmetdelicatessen.co.uk
Reid,Euresti,M,56,"Fitzgerald, Edward J",70 Foster St,Inverness Ness-Side Ward,Highland,IV2 6WT,01916-963261,01370-319414,reuresti@euresti.co.uk,http://www.fitzgeraldedwardj.co.uk
Charlette,Brenning,F,31,Furey & Associates,714 Fonthill Rd,Darton West Ward,South Yorkshire,S75 5EJ,01888-152110,01301-312487,cbrenning@brenning.co.uk,http://www.fureyassociates.co.uk
Celestina,Keeny,F,41,Bfg Federal Credit Union,9 Milton St,Consett North ED,County Durham,DH8 5LP,01877-379681,01600-463475,celestina_keeny@gmail.com,http://www.bfgfederalcreditunion.co.uk
Mi,Richan,M,27,Nelson Wright Haworth Golf Crs,6 Norwood Grove,Tanworth-in-Arden,Warwickshire,B94 5RZ,01451-785624,01202-738406,mi@hotmail.com,http://www.nelsonwrighthaworthgolfcrs.co.uk