In [9]:
import pandas as pd
df_customer = pd.read_csv("Resources/Week3-Day3-Activity7customer_info.csv",index_col="CustomerID")
df_fr = pd.read_csv("Resources/Week3-Day3-Activity7france_products.csv",index_col="CustomerID")
df_nl = pd.read_csv("Resources/Week3-Day3-Activity7netherlands_products.csv",index_col="CustomerID")
df_products = pd.read_csv("Resources/Week3-Day3-Activity7products.csv",index_col="CustomerID")
df_uk = pd.read_csv("Resources/Week3-Day3-Activity7uk_products.csv",index_col="CustomerID")

In [10]:
df_customer.head(10)

,FirstName,LastName,Address,City,Postal,Country,JoinDate
CustomerID,,,,,,,
12583,Christine,Lagarde,26 rue des Nations Unies,SAINT-BENOÎT,97470,France,2012-09-12
17069,John,Grayken,73 Red Lane,Evershot,DT2 5JB,UK,2010-04-24
14646,Frits,Goldschmeding,Nassaupark 84,Bussum,1405 HP,Holland,2017-01-19

In [13]:
df_fr.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
CustomerID,,,,,,,
12583,536370,10002,INFLATABLE POLITICAL GLOBE,48,12/1/2010 8:45,0.85,France
12583,536370,21791,VINTAGE HEADS AND TAILS CARD GAME,24,12/1/2010 8:45,1.25,France
12583,536370,21035,SET/2 RED RETROSPOT TEA TOWELS,18,12/1/2010 8:45,2.95,France
12583,536370,22326,ROUND SNACK BOXES SET OF4 WOODLAND,24,12/1/2010 8:45,2.95,France
12583,536370,22629,SPACEBOY LUNCH BOX,24,12/1/2010 8:45,1.95,France
12583,536370,22659,LUNCH BOX I LOVE LONDON,24,12/1/2010 8:45,1.95,France
12583,536370,22544,MINI JIGSAW SPACEBOY,24,12/1/2010 8:45,0.42,France

In [14]:
df_nl.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
CustomerID,,,,,,,
14646,539491,21981,PACK OF 12 WOODLAND TISSUES,12,12/20/2010 10:09,0.29,Netherlands
14646,539491,21986,PACK OF 12 PINK POLKADOT TISSUES,12,12/20/2010 10:09,0.29,Netherlands
14646,539491,21123,SET/10 IVORY POLKADOT PARTY CANDLES,2,12/20/2010 10:09,1.25,Netherlands
14646,539491,47599A,PINK PARTY BAGS,2,12/20/2010 10:09,2.10,Netherlands
14646,539491,22331,WOODLAND PARTY BAG + STICKER SET,2,12/20/2010 10:09,1.65,Netherlands
14646,539491,22333,RETROSPOT PARTY BAG + STICKER SET,2,12/20/2010 10:09,1.65,Netherlands
14646,539491,22315,200 RED + WHITE BENDY STRAWS,1,12/20/2010 10:09,1.25,Netherlands
14646,539491,22445,PENCIL CASE LIFE IS BEAUTIFUL,1,12/20/2010 10:09,2.95,Netherlands

In [15]:
df_uk.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
CustomerID,,,,,,,
17069,539490,22720,SET OF 3 CAKE TINS PANTRY DESIGN,6,12/20/2010 10:00,4.95,United Kingdom
17069,539490,22721,SET OF 3 CAKE TINS SKETCHBOOK,3,12/20/2010 10:00,4.95,United Kingdom
17069,539490,22722,SET OF 6 SPICE TINS PANTRY DESIGN,8,12/20/2010 10:00,3.95,United Kingdom
17069,539490,22723,SET OF 6 HERB TINS SKETCHBOOK,4,12/20/2010 10:00,3.95,United Kingdom
17069,539490,22961,JAM MAKING SET PRINTED,12,12/20/2010 10:00,1.45,United Kingdom
17069,539490,22178,VICTORIAN GLASS HANGING T-LIGHT,12,12/20/2010 10:00,1.25,United Kingdom
17069,539490,84997A,GREEN 3 PIECE POLKADOT CUTLERY SET,6,12/20/2010 10:00,3.75,United Kingdom

In [16]:
df_products.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
CustomerID,,,,,,,
14646,539491,21981,PACK OF 12 WOODLAND TISSUES,12,12/20/2010 10:09,0.29,Netherlands
17069,539490,22665,RECIPE BOX BLUE SKETCHBOOK DESIGN,12,12/20/2010 10:00,2.95,United Kingdom
12583,540455,22726,ALARM CLOCK BAKELIKE GREEN,16,1/7/2011 12:07,3.75,France

In [21]:
df_summary = pd.concat([df_uk,df_nl,df_fr,df_products])
df_summary.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
CustomerID,,,,,,,
17069,539490,22720,SET OF 3 CAKE TINS PANTRY DESIGN,6,12/20/2010 10:00,4.95,United Kingdom
17069,539490,22721,SET OF 3 CAKE TINS SKETCHBOOK,3,12/20/2010 10:00,4.95,United Kingdom
17069,539490,22722,SET OF 6 SPICE TINS PANTRY DESIGN,8,12/20/2010 10:00,3.95,United Kingdom
17069,539490,22723,SET OF 6 HERB TINS SKETCHBOOK,4,12/20/2010 10:00,3.95,United Kingdom
17069,539490,22961,JAM MAKING SET PRINTED,12,12/20/2010 10:00,1.45,United Kingdom
17069,539490,22178,VICTORIAN GLASS HANGING T-LIGHT,12,12/20/2010 10:00,1.25,United Kingdom
17069,539490,84997A,GREEN 3 PIECE POLKADOT CUTLERY SET,6,12/20/2010 10:00,3.75,United Kingdom
14646,539491,21981,PACK OF 12 WOODLAND TISSUES,12,12/20/2010 10:09,0.29,Netherlands
14646,539491,21986,PACK OF 12 PINK POLKADOT TISSUES,12,12/20/2010 10:09,0.29,Netherlands
14646,539491,21123,SET/10 IVORY POLKADOT PARTY CANDLES,2,12/20/2010 10:09,1.25,Netherlands

In [24]:
df_summary.duplicated().mean()

0.0

In [25]:
df_summary.drop_duplicates()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
CustomerID,,,,,,,
17069,539490,22720,SET OF 3 CAKE TINS PANTRY DESIGN,6,12/20/2010 10:00,4.95,United Kingdom
17069,539490,22721,SET OF 3 CAKE TINS SKETCHBOOK,3,12/20/2010 10:00,4.95,United Kingdom
17069,539490,22722,SET OF 6 SPICE TINS PANTRY DESIGN,8,12/20/2010 10:00,3.95,United Kingdom
17069,539490,22723,SET OF 6 HERB TINS SKETCHBOOK,4,12/20/2010 10:00,3.95,United Kingdom
17069,539490,22961,JAM MAKING SET PRINTED,12,12/20/2010 10:00,1.45,United Kingdom
17069,539490,22178,VICTORIAN GLASS HANGING T-LIGHT,12,12/20/2010 10:00,1.25,United Kingdom
17069,539490,84997A,GREEN 3 PIECE POLKADOT CUTLERY SET,6,12/20/2010 10:00,3.75,United Kingdom
14646,539491,21981,PACK OF 12 WOODLAND TISSUES,12,12/20/2010 10:09,0.29,Netherlands
14646,539491,21986,PACK OF 12 PINK POLKADOT TISSUES,12,12/20/2010 10:09,0.29,Netherlands
14646,539491,21123,SET/10 IVORY POLKADOT PARTY CANDLES,2,12/20/2010 10:09,1.25,Netherlands
14646,539491,47599A,PINK PARTY BAGS,2,12/20/2010 10:09,2.10,Netherlands
14646,539491,22331,WOODLAND PARTY BAG + STICKER SET,2,12/20/2010 10:09,1.65,Netherlands
14646,539491,22333,RETROSPOT PARTY BAG + STICKER SET,2,12/20/2010 10:09,1.65,Netherlands
14646,539491,22315,200 RED + WHITE BENDY STRAWS,1,12/20/2010 10:09,1.25,Netherlands
14646,539491,22445,PENCIL CASE LIFE IS BEAUTIFUL,1,12/20/2010 10:09,2.95,Netherlands
12583,536370,10002,INFLATABLE POLITICAL GLOBE,48,12/1/2010 8:45,0.85,France
12583,536370,21791,VINTAGE HEADS AND TAILS CARD GAME,24,12/1/2010 8:45,1.25,France
12583,536370,21035,SET/2 RED RETROSPOT TEA TOWELS,18,12/1/2010 8:45,2.95,France
12583,536370,22326,ROUND SNACK BOXES SET OF4 WOODLAND,24,12/1/2010 8:45,2.95,France
12583,536370,22629,SPACEBOY LUNCH BOX,24,12/1/2010 8:45,1.95,France
12583,536370,22659,LUNCH BOX I LOVE LONDON,24,12/1/2010 8:45,1.95,France
12583,536370,22544,MINI JIGSAW SPACEBOY,24,12/1/2010 8:45,0.42,France
14646,539491,21981,PACK OF 12 WOODLAND TISSUES,12,12/20/2010 10:09,0.29,Netherlands
17069,539490,22665,RECIPE BOX BLUE SKETCHBOOK DESIGN,12,12/20/2010 10:00,2.95,United Kingdom
12583,540455,22726,ALARM CLOCK BAKELIKE GREEN,16,1/7/2011 12:07,3.75,France

In [26]:
len(df_customer)

3

In [28]:
df_summary_with_Customer_Data = pd.merge(df_summary,df_customer,how='left',left_on = df_summary.index, right_on = df_customer.index)
df_summary_with_Customer_Data

,key_0,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country_x,FirstName,LastName,Address,City,Postal,Country_y,JoinDate
0,17069,539490,22720,SET OF 3 CAKE TINS PANTRY DESIGN,6,12/20/2010 10:00,4.95,United Kingdom,John,Grayken,73 Red Lane,Evershot,DT2 5JB,UK,2010-04-24
1,17069,539490,22721,SET OF 3 CAKE TINS SKETCHBOOK,3,12/20/2010 10:00,4.95,United Kingdom,John,Grayken,73 Red Lane,Evershot,DT2 5JB,UK,2010-04-24
2,17069,539490,22722,SET OF 6 SPICE TINS PANTRY DESIGN,8,12/20/2010 10:00,3.95,United Kingdom,John,Grayken,73 Red Lane,Evershot,DT2 5JB,UK,2010-04-24
3,17069,539490,22723,SET OF 6 HERB TINS SKETCHBOOK,4,12/20/2010 10:00,3.95,United Kingdom,John,Grayken,73 Red Lane,Evershot,DT2 5JB,UK,2010-04-24
4,17069,539490,22961,JAM MAKING SET PRINTED,12,12/20/2010 10:00,1.45,United Kingdom,John,Grayken,73 Red Lane,Evershot,DT2 5JB,UK,2010-04-24
5,17069,539490,22178,VICTORIAN GLASS HANGING T-LIGHT,12,12/20/2010 10:00,1.25,United Kingdom,John,Grayken,73 Red Lane,Evershot,DT2 5JB,UK,2010-04-24
6,17069,539490,84997A,GREEN 3 PIECE POLKADOT CUTLERY SET,6,12/20/2010 10:00,3.75,United Kingdom,John,Grayken,73 Red Lane,Evershot,DT2 5JB,UK,2010-04-24
7,14646,539491,21981,PACK OF 12 WOODLAND TISSUES,12,12/20/2010 10:09,0.29,Netherlands,Frits,Goldschmeding,Nassaupark 84,Bussum,1405 HP,Holland,2017-01-19
8,14646,539491,21986,PACK OF 12 PINK POLKADOT TISSUES,12,12/20/2010 10:09,0.29,Netherlands,Frits,Goldschmeding,Nassaupark 84,Bussum,1405 HP,Holland,2017-01-19
9,14646,539491,21123,SET/10 IVORY POLKADOT PARTY CANDLES,2,12/20/2010 10:09,1.25,Netherlands,Frits,Goldschmeding,Nassaupark 84,Bussum,1405 HP,Holland,2017-01-19
10,14646,539491,47599A,PINK PARTY BAGS,2,12/20/2010 10:09,2.10,Netherlands,Frits,Goldschmeding,Nassaupark 84,Bussum,1405 HP,Holland,2017-01-19
11,14646,539491,22331,WOODLAND PARTY BAG + STICKER SET,2,12/20/2010 10:09,1.65,Netherlands,Frits,Goldschmeding,Nassaupark 84,Bussum,1405 HP,Holland,2017-01-19
12,14646,539491,22333,RETROSPOT PARTY BAG + STICKER SET,2,12/20/2010 10:09,1.65,Netherlands,Frits,Goldschmeding,Nassaupark 84,Bussum,1405 HP,Holland,2017-01-19
13,14646,539491,22315,200 RED + WHITE BENDY STRAWS,1,12/20/2010 10:09,1.25,Netherlands,Frits,Goldschmeding,Nassaupark 84,Bussum,1405 HP,Holland,2017-01-19
14,14646,539491,22445,PENCIL CASE LIFE IS BEAUTIFUL,1,12/20/2010 10:09,2.95,Netherlands,Frits,Goldschmeding,Nassaupark 84,Bussum,1405 HP,Holland,2017-01-19
15,12583,536370,10002,INFLATABLE POLITICAL GLOBE,48,12/1/2010 8:45,0.85,France,Christine,Lagarde,26 rue des Nations Unies,SAINT-BENOÎT,97470,France,2012-09-12
16,12583,536370,21791,VINTAGE HEADS AND TAILS CARD GAME,24,12/1/2010 8:45,1.25,France,Christine,Lagarde,26 rue des Nations Unies,SAINT-BENOÎT,97470,France,2012-09-12
17,12583,536370,21035,SET/2 RED RETROSPOT TEA TOWELS,18,12/1/2010 8:45,2.95,France,Christine,Lagarde,26 rue des Nations Unies,SAINT-BENOÎT,97470,France,2012-09-12
18,12583,536370,22326,ROUND SNACK BOXES SET OF4 WOODLAND,24,12/1/2010 8:45,2.95,France,Christine,Lagarde,26 rue des Nations Unies,SAINT-BENOÎT,97470,France,2012-09-12
19,12583,536370,22629,SPACEBOY LUNCH BOX,24,12/1/2010 8:45,1.95,France,Christine,Lagarde,26 rue des Nations Unies,SAINT-BENOÎT,97470,France,2012-09-12
20,12583,536370,22659,LUNCH BOX I LOVE LONDON,24,12/1/2010 8:45,1.95,France,Christine,Lagarde,26 rue des Nations Unies,SAINT-BENOÎT,97470,France,2012-09-12
21,12583,536370,22544,MINI JIGSAW SPACEBOY,24,12/1/2010 8:45,0.42,France,Christine,Lagarde,26 rue des Nations Unies,SAINT-BENOÎT,97470,France,2012-09-12
22,14646,539491,21981,PACK OF 12 WOODLAND TISSUES,12,12/20/2010 10:09,0.29,Netherlands,Frits,Goldschmeding,Nassaupark 84,Bussum,1405 HP,Holland,2017-01-19
23,17069,539490,22665,RECIPE BOX BLUE SKETCHBOOK DESIGN,12,12/20/2010 10:00,2.95,United Kingdom,John,Grayken,73 Red Lane,Evershot,DT2 5JB,UK,2010-04-24
24,12583,540455,22726,ALARM CLOCK BAKELIKE GREEN,16,1/7/2011 12:07,3.75,France,Christine,Lagarde,26 rue des Nations Unies,SAINT-BENOÎT,97470,France,2012-09-12